Repository carloscastrojumo/github-cherry-pick-action, pull requests merged in 2023-02, with the labels that each got.

#57 Update example in README for merge condition
  README.md
Labels: bug

#58 Fix branch for changelog action
  .github/workflows/changelog.yaml
Labels: bug

#59 Fix token name
  .github/workflows/changelog.yaml
Labels: bug

#60 Fix release actions
  .github/workflows/changelog.yaml
Labels: bug

#61 Another attempt to fix release
  .github/configuration.json
  .github/release-drafter.yml
  .github/workflows/changelog.yaml
Labels: bug

#62 Revert
  .github/configuration.json
  .github/release-drafter.yml
  .github/workflows/changelog.yaml
Labels: bug

#63 Fix branch name
  .github/workflows/changelog.yaml
Labels: bug

#64 Remove create action
  .github/workflows/changelog.yaml
  src/index.ts
Labels: maintenance

#65 New release action
  .github/configuration.json
  .github/release-drafter.yml
  .github/workflows/changelog.yaml
Labels: maintenance

#66 Update token to GITHUB_TOKEN
  .github/workflows/changelog.yaml
Labels: maintenance

#72 [ISSUE-44] Get commit SHA from pull_request.merge_commit_sha
  README.md
  src/index.ts
  test/index.test.ts
Labels: enhancement

#79 Auto label dependabot Pull Requests
  .github/workflows/autolabel.yaml
Labels: maintenance

#81 Fix Auto label dependabot Pull Requests
  .github/workflows/autolabel.yaml
Labels: maintenance
